export const liveContests = [
  {
    id: "WC-43L",
    name: "Weekly Contest #43",
    desc: "Graph Algorithms & Greedy Techniques",
    date: "Mar 15, 2025",
    time: "14:00 UTC",
    duration: "2h",
    problems: 4,
    participants: 892,
    tags: ["Graphs", "Greedy", "Trees", "Shortest Path"],
  },
  {
    id: "BLZ-09L",
    name: "Blitz Round #9",
    desc: "Fast-Paced Implementation & Math",
    date: "Mar 15, 2025",
    time: "18:00 UTC",
    duration: "1h 30m",
    problems: 3,
    participants: 423,
    tags: ["Math", "Implementation", "Number Theory"],
  },
  {
    id: "ALG-12L",
    name: "Algorithm Sprint #12",
    desc: "Binary Search, Prefix Sum & Ad-hoc",
    date: "Mar 16, 2025",
    time: "16:00 UTC",
    duration: "2h",
    problems: 5,
    participants: 611,
    tags: ["Binary Search", "Prefix Sum", "Ad-hoc"],
  },
];

export const upcomingContests = [
  {
    id: "NC-04U",
    name: "Night Challenge #4",
    desc: "Strings, Hashing & Suffix Structures",
    date: "Mar 19, 2025",
    time: "22:00 UTC",
    duration: "2h",
    problems: 5,
    tags: ["Strings", "Hashing", "Trie", "Suffix Array"],
  },
  {
    id: "MC-09U",
    name: "Monthly Challenge #9",
    desc: "Advanced Data Structures & Optimization",
    date: "Mar 22, 2025",
    time: "10:00 UTC",
    duration: "3h",
    problems: 8,
    tags: ["Segment Tree", "BIT", "Persistent"],
  },
  {
    id: "WC-44U",
    name: "Weekly Contest #44",
    desc: "Dynamic Programming & Combinatorics",
    date: "Mar 29, 2025",
    time: "14:00 UTC",
    duration: "2h",
    problems: 4,
    tags: ["DP", "Combinatorics", "Probability"],
  },
];

export const pastContests = [
  {
    id: "WC-42",
    name: "Weekly Contest #42",
    date: "Mar 8, 2025",
    type: "Weekly",
    participated: true,
    rank: 12,
    total: 847,
    questions: 5,
    rated: true,
    tags: ["Graphs", "Trees", "Greedy"],
  },
  {
    id: "BLZ-08",
    name: "Blitz Round #8",
    date: "Mar 6, 2025",
    type: "Blitz",
    participated: false,
    rank: null,
    total: 389,
    questions: 3,
    rated: false,
    tags: ["Math", "Implementation"],
  },
  {
    id: "WC-41",
    name: "Weekly Contest #41",
    date: "Mar 1, 2025",
    type: "Weekly",
    participated: true,
    rank: 18,
    total: 823,
    questions: 5,
    rated: true,
    tags: ["Arrays", "Binary Search", "Two Pointers"],
  },
  {
    id: "MC-08",
    name: "Monthly Challenge #8",
    date: "Feb 22, 2025",
    type: "Monthly",
    participated: false,
    rank: null,
    total: 1245,
    questions: 8,
    rated: true,
    tags: ["Segment Tree", "BIT", "String"],
  },
];
export const contestFilters = [
  { key: "all", label: "All" },
  { key: "live", label: "Live" },
  { key: "upcoming", label: "Upcoming" },
  { key: "past", label: "Past" },
];
