export const liveContests = [
  {
    id: "WC-43L",
    name: "Weekly Contest #43",
    desc: "Graph Algorithms & Greedy Techniques",
    date: "Mar 15, 2025",
    time: "14:00 UTC",
    duration: "2h",
    problems: 4,
    participants: 892,
    requiresPassword: false,
    password: "",
    tags: ["Graphs", "Greedy", "Trees", "Shortest Path"],
  },
  {
    id: "BLZ-09L",
    name: "Blitz Round #9",
    desc: "Fast-Paced Implementation & Math",
    date: "Mar 15, 2025",
    time: "18:00 UTC",
    duration: "1h 30m",
    problems: 3,
    participants: 423,
    requiresPassword: true,
    password: "quick12",
    tags: ["Math", "Implementation", "Number Theory"],
  },
  {
    id: "ALG-12L",
    name: "Algorithm Sprint #12",
    desc: "Binary Search, Prefix Sum & Ad-hoc",
    date: "Mar 16, 2025",
    time: "16:00 UTC",
    duration: "2h",
    problems: 5,
    participants: 611,
    requiresPassword: false,
    password: "",
    tags: ["Binary Search", "Prefix Sum", "Ad-hoc"],
  },
];
export const upcomingContests = [
  {
    id: "NC-04U",
    name: "Night Challenge #4",
    desc: "Strings, Hashing & Suffix Structures",
    date: "Mar 19, 2025",
    time: "22:00 UTC",
    duration: "2h",
    problems: 5,
    registered: false,
    tags: ["Strings", "Hashing", "Trie", "Suffix Array"],
  },
  {
    id: "MC-09U",
    name: "Monthly Challenge #9",
    desc: "Advanced Data Structures & Optimization",
    date: "Mar 22, 2025",
    time: "10:00 UTC",
    duration: "3h",
    problems: 8,
    registered: true,
    tags: ["Segment Tree", "BIT", "Persistent"],
  },
  {
    id: "WC-44U",
    name: "Weekly Contest #44",
    desc: "Dynamic Programming & Combinatorics",
    date: "Mar 29, 2025",
    time: "14:00 UTC",
    duration: "2h",
    problems: 4,
    registered: true,
    tags: ["DP", "Combinatorics", "Probability"],
  },
];
export const pastContests = [
  {
    id: "WC-42",
    name: "Weekly Contest #42",
    date: "Mar 8, 2025",
    type: "Weekly",
    participated: true,
    rank: 12,
    total: 847,
    questions: 5,
    rated: true,
    tags: ["Graphs", "Trees", "Greedy"],
  },
  {
    id: "BLZ-08",
    name: "Blitz Round #8",
    date: "Mar 6, 2025",
    type: "Blitz",
    participated: false,
    rank: null,
    total: 389,
    questions: 3,
    rated: false,
    tags: ["Math", "Implementation"],
  },
  {
    id: "WC-41",
    name: "Weekly Contest #41",
    date: "Mar 1, 2025",
    type: "Weekly",
    participated: true,
    rank: 18,
    total: 823,
    questions: 5,
    rated: true,
    tags: ["Arrays", "Binary Search", "Two Pointers"],
  },
  {
    id: "MC-08",
    name: "Monthly Challenge #8",
    date: "Feb 22, 2025",
    type: "Monthly",
    participated: false,
    rank: null,
    total: 1245,
    questions: 8,
    rated: true,
    tags: ["Segment Tree", "BIT", "String"],
  },
  {
    id: "NC-03",
    name: "Night Challenge #3",
    date: "Feb 19, 2025",
    type: "Night",
    participated: true,
    rank: 7,
    total: 512,
    questions: 5,
    rated: false,
    tags: ["Strings", "Hashing", "Trie"],
  },
  {
    id: "WC-40",
    name: "Weekly Contest #40",
    date: "Feb 15, 2025",
    type: "Weekly",
    participated: true,
    rank: 24,
    total: 801,
    questions: 5,
    rated: true,
    tags: ["Graphs", "DFS", "BFS", "Shortest Path"],
  },
  {
    id: "WC-39",
    name: "Weekly Contest #39",
    date: "Feb 8, 2025",
    type: "Weekly",
    participated: true,
    rank: 8,
    total: 789,
    questions: 5,
    rated: true,
    tags: ["DP", "Greedy", "Math", "Combinatorics"],
  },
  {
    id: "BLZ-07",
    name: "Blitz Round #7",
    date: "Feb 6, 2025",
    type: "Blitz",
    participated: false,
    rank: null,
    total: 367,
    questions: 3,
    rated: false,
    tags: ["Implementation", "Simulation"],
  },
  {
    id: "MC-07",
    name: "Monthly Challenge #7",
    date: "Jan 25, 2025",
    type: "Monthly",
    participated: true,
    rank: 45,
    total: 1189,
    questions: 8,
    rated: true,
    tags: ["Persistent", "Heavy Light", "LCA", "DP"],
  },
  {
    id: "NR-01",
    name: "New Year Special",
    date: "Jan 1, 2025",
    type: "Special",
    participated: true,
    rank: 6,
    total: 2103,
    questions: 7,
    rated: true,
    tags: ["Mixed", "Advanced", "All Topics"],
  },
  {
    id: "WC-38",
    name: "Weekly Contest #38",
    date: "Dec 28, 2024",
    type: "Weekly",
    participated: false,
    rank: null,
    total: 776,
    questions: 5,
    rated: true,
    tags: ["Trees", "Binary Search", "Stack"],
  },
  {
    id: "MC-06",
    name: "Monthly Challenge #6",
    date: "Dec 21, 2024",
    type: "Monthly",
    participated: true,
    rank: 38,
    total: 1123,
    questions: 8,
    rated: true,
    tags: ["Graphs", "DP", "Number Theory", "Segment Tree"],
  },
];
export const contestFilters = [
  { key: "all", label: "All" },
  { key: "live", label: "Live" },
  { key: "upcoming", label: "Upcoming" },
  { key: "past", label: "Past" },
];
